config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
]

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views


# 네임스페이스
app_name = 'pybo'

urlpatterns = [
	# base_views.py
	path("", base_views.index, name='index'),
	path("<int:question_id>/", base_views.detail, name='detail'),

	# question_views.py
	path("question/create/", question_views.question_create, name='question_create'),
	path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
	path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

	# answer_views.py
	path("answer/create/<int:question_id>/", answer_views.answer_create, name='answer_create'),
	path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
	path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

	# comment_views.py
	path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
	path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
	path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
	path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
	path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
	path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

	# vote_views.py
	path('vote/question/<int:question_id>/', vote_views.vote_question, name="vote_question"),
	path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name="vote_answer"),
]

pybo/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    # Question 모델에서 사용하는 author과 voter 필드가 모두 User 모델을 참조하고 있는데,
    # 추후 User.question_set과 같이 User 모델을 통해 Question데이터에 접근할 경우
    # author 필드를 기준으로 할지 voter 필드를 기준으로 할지 related_name 옵션을 추가하여 설정
    # 특정 사용자가 작성한 질문을 얻기 위해 some_user.author_question.all() 사용
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    # 글 1개에 여러 명이 추천할 수 있으며, 1명이 여러 개의 글을 추천 할 수 있어서 다대다 관계로 설정
    # 특정 사용자가 추천한 질문을 얻기 위한 코드는 some_user.voter_question.all()
    # ManyToManyField 필드는 중복을 허락하지 않는다.
    voter = models.ManyToManyField(User, related_name='voter_question')
    create_date = models.DateTimeField()
    # modify_date에 Null 허용
    # blank=True는 form.is_valid()를 통한 입력 폰 데이터 검사 시 값이 없어도 된다는 의미
    modify_date = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return self.subject


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    voter = models.ManyToManyField(User, related_name='voter_answer')
    modify_date = models.DateTimeField(null=True, blank=True)


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(Question, null=True, blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, null=True, blank=True, on_delete=models.CASCADE)

pybo/views/answer_views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from ..models import Answer, Question
from ..forms import AnswerForm


@login_required(login_url='common:login')
def answer_create(request, question_id):
    """
        pybo 답변 등록
        :param request:
        :param question_id: question 레코드 아이디
        :return:
    """

    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            # request.user 현재 로그인한 계정의 User 모델 객체
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=question.id), answer.id))
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    """
        답변 수정
        :param request:
        :param answer_id: 답변 레코드 아이디
        :return:
    """

    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=answer.question.id)

    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    """
        답변 삭제
        :param request:
        :param answer_id: 답변 레코드 아이디
        :return:
    """

    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다.')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

pybo/views/base_views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Q, Count

from ..models import Question


def index(request):
    """
        질문 목록 출력
        :param request:
        :return:
    """

    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    so = request.GET.get('so', 'recent')

    if so == 'recommend':
        # annotate 함수는 Question 모델의 기존 필드인 author, subject, content, create_date, modify_date, voter에 질문의 추천 수에 해당하는 num_voter필드를 임시로 추가해 주는 함수
        # 이렇게 annotate함수로 nom_voter필드를 추가하면 filter 함수나 order_by 함수에서 num_voter 필드를 사용할 수 있게 된다.
        # Count('voter')는 해당 질문의 추천 수이다.
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:
        question_list = Question.objects.order_by('-create_date')

    if kw:
        # Q 함수에 사용된 subject__icontains=kw 는 제목에 kw 문자열이 포함되었는지를 의미
        question_list = question_list.filter(
            Q(subject__icontains=kw) |   # 제목 검색
            Q(content__icontains=kw) |   # 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)   # 답변 글쓴이 검색
        ).distinct()

    # paging
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여 주기
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so': so}
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    """
        특정 질문 내용 출력
        :param request:
        :param question_id: 질문 레코드 아이디
        :return:
    """
    page = request.GET.get('page', '1')
    question = get_object_or_404(Question, pk=question_id)

    # paging
    answers = question.answer_set.all()
    paginator = Paginator(answers, 2)  # 페이지당 2개씩 보여 주기
    page_obj = paginator.get_page(page)

    context = {'question': question, 'answers': page_obj, 'page': page}

    return render(request, 'pybo/question_detail.html', context)

pybo/views/comment_views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from ..models import Answer, Question, Comment
from ..forms import CommentForm


@login_required(login_url='common:login')
def comment_create_question(request, question_id):
    """
        pybo 질문 댓글 등록
        :param request:
        :param question_id: 질문 레코드 아이디
        :return:
    """

    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.question = question
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.question.id), comment.id))
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_question(request, comment_id):
    """
        pybo 질문 댓글 수정
        :param request:
        :param comment_id: 댓글 레코드 아이디
        :return:
    """

    comment = get_object_or_404(Comment, pk=comment_id)

    if request.user != comment.author:
        messages.error(request, '댓글 수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.question.id)

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.question.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_question(request, comment_id):
    """
        pybo 질문 댓글 삭제
        :param request:
        :param comment_id: 댓글 레코드 아이디
        :return:
    """

    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글 삭제권한이 없습니다.')
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.question.id)


@login_required(login_url='common:login')
def comment_create_answer(request, answer_id):
    """
        pybo 답변 댓글 등록
        :param request:
        :param answer_id: 답변 레코드 아이디
        :return:
    """

    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.answer = answer
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.answer.question.id), comment.id))
    else:
        form = CommentForm()
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_modify_answer(request, comment_id):
    """
        pybo 답변 댓글 수정
        :param request:
        :param comment_id: 댓글 레코드 아이디
        :return:
    """

    comment = get_object_or_404(Comment, pk=comment_id)

    if request.user != comment.author:
        messages.error(request, '댓글 수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=comment.answer.question.id)

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#comment_{}'.format(resolve_url('pybo:detail', question_id=comment.answer.question.id), comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)


@login_required(login_url='common:login')
def comment_delete_answer(request, comment_id):
    """
        pybo 답변 댓글 삭제
        :param request:
        :param comment_id: 댓글 레코드 아이디
        :return:
    """

    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '댓글 삭제권한이 없습니다.')
    else:
        comment.delete()
    return redirect('pybo:detail', question_id=comment.answer.question.id)

pybo/views/question_views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone

from ..models import Question
from ..forms import QuestionForm


@login_required(login_url='common:login')
def question_create(request):
    """
        pybo 질문 등록
        :param request:
        :return:
    """

    if request.method == 'POST':
        form = QuestionForm(request.POST)
        # 요청 받은 form이 유효한지 검사
        if form.is_valid():
            # commit=False는 임시 저장을 의미하며 데이터가 실제 저장 되지 않는다.
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        # method == 'GET'
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_modify(request, question_id):
    """
        pybo 질문 수정
        :param request:
        :param question_id: 질문 레코드 아이디
        :return:
    """

    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=question.id)

    if request.method == 'POST':
        # question을 기본값으로 하여 화면으로 전달받은 입력값들을 덮어써서 QuestionForm을 생성하라는 의미
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.modify_date = timezone.now()
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        # instance=question 지정하면 기존 값을 폼에 채울 수 있다.
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request, question_id):
    """
        pybo 질문 삭제
        :param request:
        :param question_id: 질문 레코드 아이디
        :return:
    """

    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다.')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')

pybo/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from ..models import Question, Answer


@login_required(login_url='common:login')
def vote_question(request, question_id):
    """
        pybo 질문 추천 등록
        :param request:
        :param question_id:
        :return:
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천 할 수 없습니다.')
    else:
        question.voter.add(request.user)
    return redirect('pybo:detail', question_id=question.id)


@login_required(login_url='common:login')
def vote_answer(request, answer_id):
    """
        pybo 답변 추천 등록
        :param request:
        :param answer_id:
        :return:
    """
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천 할 수 없습니다.')
    else:
        answer.voter.add(request.user)
    return redirect('pybo:detail', question_id=answer.question.id)

templates/pybo/answer_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
  <form method="post" class="post-form">
    {% csrf_token %}
    {% include 'form_errors.html' %}
    <div class="form-group">
      <label for="content">답변내용</label>
      <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>
{% endblock %}

templates/pybo/comment_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
  <h5 class="border-bottom pb-2">댓글등록하기</h5>
  <form method="post" class="post-form my-3">
    {% csrf_token %}
    {% include "form_errors.html" %}
    <div class="form-group">
      <label for="content">댓글내용</label>
      <textarea class="form-control" name="content" id="content" rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% load pybo_filter %}

{% block content %}
<div class="container my-3">
    <!-- 사용자 오류 표시 -->
    {% if messages %}
        <div class="alert alert-danger my-3" role="alert">
            {% for message in messages %}
                <strong> {{ messages.tags }}</strong>
                <ul><li>{{ message.message }}</li></ul>
            {% endfor %}
        </div>
    {% endif %}

    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="row my-3">
        <div class="col-1">
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
                {{ question.voter.count }}
            </div>
            <a href="#" data-uri="{% url 'pybo:vote_question' question.id %}" class="recommend btn btn-sm btn-secondary btn-block my1">추천</a>
        </div>
        <div class="col-11">
            <div class="card">
                <div class="card-body">
                    <div class="card-text">
                        {{ question.content|mark }}
                    </div>
                    <div class="d-flex justify-content-end">
                        {% if question.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2"> modified at </div>
                            <div>{{ question.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="'badge badge-light p-2 text-left">
                            <div class="mb-2"> {{ question.author.username }}</div>
                            <div>{{ question.create_date }}</div>
                        </div>
                    </div>
                    <!-- 질문 수정 버튼은 로그인한 사용자와 글쓴이가 같은 경우에만 보여야 한다. -->
                    {% if request.user == question.author %}
                    <div class="my-3">
                        <a href="{% url 'pybo:question_modify' question.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:question_delete' question.id %}">삭제</a>
                    </div>
                    {% endif %}
                    {% if question.comment_set.count > 0 %}
                    <div class="mt-3">
                        {% for comment in question.comment_set.all %}
                        <a name="comment_{{ comment.id }}"></a>
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                                    - {{ comment.author }}, {{comment.create_date }}
                                    {% if comment.modify_date %}
                                        (수정:{{ comment.modify_date }})
                                    {% endif %}
                                </span>
                            {% if request.user == comment.author %}
                            <a href="{% url 'pybo:comment_modify_question' comment.id %}" class="small">수정</a>
                            <a href="#" class="small delete" data-uri="{% url 'pybo:comment_delete_question' comment.id %}">삭제</a>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'pybo:comment_create_question' question.id %}" class="small"><small>댓글 추가</small></a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <br><br>
    <div>
        <!-- 질문에 대한 답변 -->
        <h5 class="border-bottom my-3 py-2">{{ question.answer_set.count}}개의 답변이 있습니다.</h5>
        {% for answer in answers %}
            <a name="answer_{{ answer.id }}"></a>
            <div class="row my-3">
                <div class="col-1">
                    <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
                        {{ answer.voter.count }}
                    </div>
                    <a href="#" data-uri="{% url 'pybo:vote_answer' answer.id %}" class="recommend btn btn-sm btn-secondary btn-block my1">추천</a>
                </div>
                <div class="col-11">
                    <div class="card">
                <div class="card-body">
                    <div class="card-text">
                        {{ answer.content|mark }}
                    </div>
                    <div class="d-flex justify-content-end">
                        {% if answer.modify_date %}
                            <div class="badge badge-light p-2 text-left mx-3">
                                <div class="mb-2"> modified at </div>
                                <div>{{ answer.modify_date }}</div>
                            </div>
                        {% endif %}
                        <div class="badge badge-lig ht p-2 text-left">
                            <div class="mb-2"> {{ answer.author.username }}</div>
                            <div>{{ answer.create_date }}</div>
                        </div>
                    </div>
                    <!-- 질문 수정 버튼은 로그인한 사용자와 글쓴이가 같은 경우에만 보여야 한다. -->
                    {% if request.user == answer.author %}
                        <div class="my-3">
                            <a href="{% url 'pybo:answer_modify' answer.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
                            <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'pybo:answer_delete' answer.id %}">삭제</a>
                        </div>
                    {% endif %}
                    {% if answer.comment_set.count > 0 %}
                    <div class="mt-3">
                        {% for comment in answer.comment_set.all %}
                            <a name="comment_{{ comment.id }}"></a>
                            <div class="comment py-2 text-muted">
                                <span style="white-space: pre-line;">{{ comment.content }}</span>
                                <span>
                                    - {{ comment.author }}, {{comment.create_date }}
                                    {% if comment.modify_date %}
                                        (수정:{{ comment.modify_date }})
                                    {% endif %}
                                </span>
                                {% if request.user == comment.author %}
                                    <a href="{% url 'pybo:comment_modify_answer' comment.id %}" class="small">수정</a>
                                    <a href="#" class="small delete" data-uri="{% url 'pybo:comment_delete_answer' comment.id %}">삭제</a>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
                <div>
                    <a href="{% url 'pybo:comment_create_answer' answer.id %}" class="small"><small>댓글 추가</small></a>
                </div>
                </div>
            </div>
                </div>
            </div>
        {% endfor %}

        <!-- 페이징 -->
        <ul class="pagination justify-content-center">

            <!-- 이전 페이지 -->
            {% if answers.has_previous %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ answers.previous_page_number }}" href="#">이전</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                </li>
            {% endif %}
            <!-- 페이지 리스트 -->
            {% for page_number in answers.paginator.page_range %}
                {% if page_number >= answers.number|add:-3 and page_number <= answers.number|add:3 %}
                    {% if page_number == answers.number %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
                        </li>
                    {% endif %}
                {% endif %}
            {% endfor %}
            <!-- 다음 페이지 -->
            {% if answers.has_next %}
                <li class="page-item">
                    <a class="page-link" data-page="{{ answers.next_page_number }}" href="#">다음</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                </li>
            {% endif %}
        </ul>
    </div>


    <!-- 답변 등록 form -->
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
    <!-- 아래 내용은 form 엘리먼트를 통해 전송된 데이터가 실제로 웹 브라우저에서 작성된 데이터인지 판단하는 검사기 역할을 한다.-->
        {% csrf_token %}
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                    {% if field.errors %}
                        <strong>{{ field.label }}</strong>
                        {{ field.errors }}
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
        <br><br>
        <h5>답변 등록</h5>
        <div class="form-group">
            <textarea name="content" id="content"
                      {% if not user.is_authenticated %} disabled {% endif %}
                      class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변 등록" class="btn btn-primary">
    </form>
</div>
<form id="detailSearchForm" method="get" action="{% url 'pybo:detail' question.id %}">
    <input type="hidden" id="answer_page" name="page" value="{{ page }}">
</form>
{% endblock %}

{% block script %}
<script type="text/javascript">
    $(document).ready(function() {
        $('.page-link').on('click', function() {
            $('#answer_page').val($(this).data('page'));
            $('#detailSearchForm').submit();
        });
        $('.delete').on('click', function() {
            if(confirm('정말 상제하시겠습니까?')) {
                location.href = $(this).data('uri');
            }
        });
        $(".recommend").on('click', function() {
            if(confirm('정말로 추천하시겠습니까?')) {
                location.href = $(this).data('uri');
            }
        });
    });
</script>
{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h5 class="my-3 border-bootom pb-2">질문 등록</h5>
  <form method="post" class="post-form my-3">
    {% csrf_token %}
    <!-- 오류 표시 -->
    {% if form.errors %}
      <div class="alert alert-danger" role="alert">
        {% for field in form %}
          {% if field.errors %}
          <strong> {{ field.label }} </strong>
          {% endif %}
        {% endfor %}
      </div>
    {% endif %}
<!--    {{ form.as_p }}-->
    <div class="form-group">
      <label for="subject">제목</label>
      <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:'' }}">
    </div>
    <div class="form-group">
      <label for="content">내용</label>
      <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
   </div>
    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>
{% endblock %}