common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'common'

urlpatterns = [
    # django.contrib.auth 앱의 LoginView 클래스를 활용 했으므로 별도의 views.py 파일 수정이 필요 없음!
    # LoginView는 registration/login.html 를 기본으로 호출한다. 아래처런 설정하여 common/login.html 호출하도록 변경
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
]

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views


# 네임스페이스
app_name = 'pybo'

urlpatterns = [
	# base_views.py
	path("", base_views.index, name='index'),
	path("<int:question_id>/", base_views.detail, name='detail'),

	# question_views.py
	path("question/create/", question_views.question_create, name='question_create'),
	path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
	path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

	# answer_views.py
	path("answer/create/<int:question_id>/", answer_views.answer_create, name='answer_create'),
	path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
	path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

	# comment_views.py
	path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
	path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
	path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
	path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
	path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
	path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

	# vote_views.py
	path('vote/question/<int:question_id>/', vote_views.vote_question, name="vote_question"),
	path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name="vote_answer"),
]

pybo/views/base_views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Q, Count

from ..models import Question


def index(request):
    """
        질문 목록 출력
        :param request:
        :return:
    """

    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    so = request.GET.get('so', 'recent')

    if so == 'recommend':
        # annotate 함수는 Question 모델의 기존 필드인 author, subject, content, create_date, modify_date, voter에 질문의 추천 수에 해당하는 num_voter필드를 임시로 추가해 주는 함수
        # 이렇게 annotate함수로 nom_voter필드를 추가하면 filter 함수나 order_by 함수에서 num_voter 필드를 사용할 수 있게 된다.
        # Count('voter')는 해당 질문의 추천 수이다.
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer', '-create_date')
    else:
        question_list = Question.objects.order_by('-create_date')

    if kw:
        # Q 함수에 사용된 subject__icontains=kw 는 제목에 kw 문자열이 포함되었는지를 의미
        question_list = question_list.filter(
            Q(subject__icontains=kw) |   # 제목 검색
            Q(content__icontains=kw) |   # 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)   # 답변 글쓴이 검색
        ).distinct()

    # paging
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여 주기
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page': page, 'kw': kw, 'so': so}
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    """
        특정 질문 내용 출력
        :param request:
        :param question_id: 질문 레코드 아이디
        :return:
    """
    page = request.GET.get('page', '1')
    question = get_object_or_404(Question, pk=question_id)

    # paging
    answers = question.answer_set.all()
    paginator = Paginator(answers, 2)  # 페이지당 2개씩 보여 주기
    page_obj = paginator.get_page(page)

    context = {'question': question, 'answers': page_obj, 'page': page}

    return render(request, 'pybo/question_detail.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <!-- Bootstrap CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
    {% include "navbar.html" %}
    {% block content %}
    {% endblock %}
    <!-- jQuery JS-->
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <!-- Bootstrap JS-->
    <script src="{% static 'bootstrap.min.js' %}"></script>
    {% block script %}
    {% endblock %}
</body>
</html>

templates/form_errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        <strong>{{ field.label }}</strong>
        {{ error }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      <strong>{{ error }}</strong>
    </div>
  {% endfor %}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-botton">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
                <!--  현재 로그인 상태를 판별   -->
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }}( 로그아웃 )</a>
                {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>